/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RpgManager
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/data/functions/RpgFunctions.ts
var import_obsidian = require("obsidian");
var RpgFunctions = class extends import_obsidian.Component {
  constructor(app) {
    super();
    this.app = app;
    this.initialiseRoots();
  }
  static create(app) {
    return new RpgFunctions(app);
  }
  initialiseRoots() {
    const filePath = this.app.vault.getFiles()[0].path;
    let slashCount = 0;
    let p = filePath.indexOf("/");
    while (p !== -1) {
      slashCount++;
      p = filePath.indexOf("/", p + 1);
    }
    slashCount++;
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian.TFile) {
      this.root = this.app.vault.getResourcePath(file);
    }
    if (this.root === null) {
      console.log("Rpg Manager failed to find the root folder!");
      return;
    }
    if (this.root.includes("?")) {
      this.root = this.root.substring(0, this.root.lastIndexOf("?"));
    }
    for (let removedSlash = slashCount; removedSlash > 0; removedSlash--) {
      this.root = this.root.slice(0, this.root.lastIndexOf("/"));
    }
    if (!this.root.endsWith("/")) {
      this.root += "/";
    }
    this.attachmentRoot = this.root + this.app.vault.config.attachmentFolderPath + "/";
  }
  fileExists(path) {
    const abstractFile = this.app.vault.getAbstractFileByPath(path);
    let response = false;
    if (abstractFile instanceof import_obsidian.TAbstractFile) {
      response = abstractFile ? true : false;
    }
    return response;
  }
  getImageLink(page) {
    const imageExtensions = ["jpeg", "jpg", "png", "webp"];
    for (let extensionCount = 0; extensionCount < imageExtensions.length; extensionCount++) {
      const fileName = this.app.vault.config.attachmentFolderPath + "/" + (page == null ? void 0 : page.file.name) + "." + imageExtensions[extensionCount];
      if (this.fileExists(fileName)) {
        return this.root + fileName;
      }
    }
    return null;
  }
  getImage(page, width = 75, height = 75) {
    let imageFile = null;
    if (page !== void 0) {
      imageFile = this.getImageLink(page);
    }
    let minimalDimensions = false;
    let dimensions = "width: " + width + "px; height: " + height + "px;";
    if (width !== 75 && height === 75) {
      dimensions = "width: " + width + "px;";
    } else if (width === 75 && height !== 75) {
      dimensions = "height: " + height + "px;";
    } else if (width === 75 && height === 75) {
      minimalDimensions = true;
    }
    if (imageFile === null) {
      if (!minimalDimensions) {
        return "";
      } else {
        return '<div style="' + dimensions + '"></div>';
      }
    }
    return '<img src="' + imageFile + '" style="object-fit: cover;' + dimensions + '">';
  }
  formatDate(date, type = null) {
    if (!date || date === void 0)
      return "";
    let options = null;
    if (type === "long") {
      options = {
        day: "numeric",
        month: "long",
        year: "numeric"
      };
      return date.toLocaleString(options);
    }
    if (type === "short") {
      options = {
        weekday: "short",
        month: "short",
        day: "numeric",
        year: "numeric"
      };
    }
    if (options !== null) {
      return date.toLocaleString(options);
    } else {
      return date.toISODate();
    }
  }
  formatTime(date) {
    if (!date || date === void 0)
      return "";
    const options = {
      hour12: false,
      hour: "2-digit",
      minute: "2-digit"
    };
    return date.toLocaleString(options);
  }
  calculateDuration(start, end) {
    if (!start || !end)
      return "";
    const dtStart = new Date(start);
    const dtEnd = new Date(end);
    const difference = dtEnd.valueOf() - dtStart.valueOf();
    const minutes = difference / 6e4;
    const remaining = difference - minutes * 6e4;
    const seconds = remaining > 0 ? remaining / 1e3 : 0;
    return minutes + ":" + (seconds < 10 ? "0" + seconds : seconds);
  }
  getDeathStatus(page) {
    return page.dates.death !== null ? "<br/>_(Deceased " + this.formatDate(page.dates.death) + ")_ " : "";
  }
  calculateAge(page, currentDate) {
    if (page === void 0)
      return "";
    if (!(page == null ? void 0 : page.dates.dob))
      return "";
    const end = page.dates.death || currentDate;
    const startDate = new Date(page.dates.dob);
    const endDate = new Date(end);
    const ageDifMs = endDate.valueOf() - startDate.valueOf();
    const ageDate = new Date(ageDifMs);
    return Math.abs(ageDate.getUTCFullYear() - 1970).toString();
  }
};

// src/abstracts/AbstractModel.ts
var import_obsidian3 = require("obsidian");

// src/data/validators/RpgMetadataValidator.ts
var RpgMetadataValidator = class {
  static validate(app, current) {
    let response = true;
    app.vault.getFiles().forEach((file) => {
      if (file.path === current.file.path) {
        const cache = app.metadataCache.getFileCache(file);
        if (cache != void 0 && cache.frontmatter == void 0) {
          if (cache.sections != void 0 && cache.sections[0] != void 0 && cache.sections[0].type === "yaml") {
            response = false;
          }
        }
      }
    });
    return response;
  }
};

// src/abstracts/AbstractData.ts
var AbstractData = class {
  constructor(functions, data) {
    this.functions = functions;
    this.data = data;
    this.link = data.file.link;
    this.name = data.file.name;
  }
};
var AbstractImageData = class extends AbstractData {
  constructor(functions, data) {
    super(functions, data);
    this.imageSrc = functions.getImageLink(data);
    this.image = this.imageSrc !== null ? functions.getImage(data) : "";
  }
  getImage(width = 75, height = 75) {
    if (this.imageSrc === null)
      return "";
    return this.functions.getImage(this.data, width, height);
  }
};
var AbstractDataList = class {
  constructor(campaign) {
    this.campaign = campaign;
  }
  add(data) {
    this.elements.push(data);
  }
  map(data) {
    const response = /* @__PURE__ */ new Map();
    const character = this.elements.find((t) => t.link === data.link);
    if (character !== void 0) {
      Object.entries(character).forEach(([key, value]) => {
        response.set(key, value);
      });
    }
    return response;
  }
};

// src/data/ImageData.ts
var ImageData = class extends AbstractImageData {
  constructor(functions, data, width = 75, height = 75) {
    super(functions, data);
    this.image = this.imageSrc !== null ? functions.getImage(data, width, height) : "";
  }
};

// src/views/views.ts
var views_exports = {};
__export(views_exports, {
  AdventureListView: () => AdventureListView,
  CharacterInfoView: () => CharacterInfoView,
  CharacterListView: () => CharacterListView,
  ClueListView: () => ClueListView,
  ClueStatusView: () => ClueStatusView,
  EventListView: () => EventListView,
  FactionListView: () => FactionListView,
  ImageView: () => ImageView,
  LocationListView: () => LocationListView,
  SceneListView: () => SceneListView,
  SceneNavigatorView: () => SceneNavigatorView,
  SessionListView: () => SessionListView,
  SessionNavigatorView: () => SessionNavigatorView,
  SynopsisView: () => SynopsisView,
  TimelineView: () => TimelineView
});

// src/abstracts/AbstractSingleView.ts
var AbstractSingleView = class {
  constructor(functions, app, dv) {
    this.functions = functions;
    this.app = app;
    this.dv = dv;
    this.container = dv.container;
  }
  spacer() {
    this.dv.span('<div style="height: 20px"></div>');
  }
};

// src/views/SessionNavigatorView.ts
var SessionNavigatorView = class extends AbstractSingleView {
  render(data) {
    return __async(this, null, function* () {
      const tableElements = [];
      tableElements.push(["Adventure", data.adventure ? data.adventure.link : ""]);
      tableElements.push(["Introduction", "[[#Introduction]]"]);
      tableElements.push(["ABT Plot", "[[#ABT Plot]]"]);
      tableElements.push(["Story Circle Plot", "[[#Story Circle Plot]]"]);
      tableElements.push(["Notes", "[[Notes - " + data.name + "]]"]);
      if (data.previousSession != null) {
        tableElements.push(["<< Previous Session", data.previousSession.link]);
      }
      if (data.nextSession != null) {
        tableElements.push(["Next Session >>", data.nextSession.link]);
      }
      const table = this.dv.markdownTable(["Campaign", "" + data.campaign.link], tableElements);
      this.dv.paragraph(table);
      this.spacer();
    });
  }
};

// src/views/SceneNavigatorView.ts
var SceneNavigatorView = class extends AbstractSingleView {
  render(data) {
    return __async(this, null, function* () {
      const tableElements = [];
      tableElements.push(["Adventure", data.adventure != void 0 ? data.adventure.link : ""]);
      tableElements.push(["Session", data.session != void 0 ? data.session.link : ""]);
      tableElements.push(["Session Notes", data.session != void 0 ? "[[Notes - " + data.session.name + "]]" : ""]);
      if (data.previousScene != void 0) {
        tableElements.push(["<< Previous Scene", data.previousScene.link]);
      }
      if (data.nextScene != void 0) {
        tableElements.push(["Next Scene >>", data.nextScene.link]);
      }
      const table = this.dv.markdownTable(["Campaign", "" + data.campaign.link], tableElements);
      this.dv.paragraph(table);
      this.spacer();
    });
  }
};

// src/abstracts/AbstractListView.ts
var AbstractListView = class {
  constructor(functions, app, dv) {
    this.functions = functions;
    this.app = app;
    this.dv = dv;
    this.container = dv.container;
  }
  spacer() {
    this.dv.span('<div style="height: 20px"></div>');
  }
};

// src/views/Lists/FactionListView.ts
var FactionListView = class extends AbstractListView {
  render(data) {
    return __async(this, null, function* () {
      this.dv.span("## Factions");
      this.dv.table(["", "Faction", "Synopsis"], data.elements.map((clue) => [
        clue.image,
        clue.link,
        clue.synopsis
      ]));
      this.spacer();
    });
  }
};

// src/views/CharacterInfoView.ts
var CharacterInfoView = class extends AbstractSingleView {
  render(data) {
    return __async(this, null, function* () {
      this.dv.table(["**" + data.name + "**", ""], [
        ["Status", data.isDead ? "Dead" : "Alive"],
        [data.isDead ? "Age at Death" : "Age", data.age !== "" ? data.age : "==Dob or campaign date missing=="],
        ["Goals", data.goals ? data.goals : "==Goals missing=="]
      ]);
      this.spacer();
    });
  }
};

// src/views/Lists/ClueListView.ts
var ClueListView = class extends AbstractListView {
  render(data) {
    return __async(this, null, function* () {
      this.dv.span("## Clues");
      this.dv.table(["", "Clue", "Found", "Synopsis"], data.elements.map((clue) => [
        clue.image,
        clue.link,
        clue.found,
        clue.synopsis
      ]));
      this.spacer();
    });
  }
};

// src/views/Lists/EventListView.ts
var EventListView = class extends AbstractListView {
  render(data) {
    return __async(this, null, function* () {
      this.dv.span("## Events");
      this.dv.table(["", "Name", "Date", "Synopsis"], data.elements.map((event) => [
        event.image,
        event.link,
        event.date,
        event.synopsis
      ]));
      this.spacer();
    });
  }
};

// src/views/Lists/SynopsisView.ts
var SynopsisView = class extends AbstractSingleView {
  render(data) {
    return __async(this, null, function* () {
      if (data.death !== "") {
        this.dv.span("_Deceased " + data.death + "_<br/>");
      }
      if (data.title !== null) {
        this.dv.span("## " + data.title);
      }
      let response = "";
      if (data.synopsis !== "") {
        if (data.isCharacter) {
          response = data.link + (data.death !== "" ? " was " : " is ") + data.synopsis;
        } else {
          response = data.synopsis;
        }
      } else {
        response = "==Synopsis missing==";
      }
      this.dv.span(response);
      this.spacer();
    });
  }
};

// src/views/ImageView.ts
var ImageView = class extends AbstractSingleView {
  render(data) {
    return __async(this, null, function* () {
      if (data.image !== "") {
        this.dv.span(data.image);
        this.spacer();
      }
    });
  }
};

// src/views/ClueStatusView.ts
var ClueStatusView = class extends AbstractSingleView {
  render(data) {
    return __async(this, null, function* () {
      this.dv.span((data.found === false ? "==Clue **NOT** found by the player characters==" : "_clue found by the player characters on " + data.found + "_") + "<br/>&nbsp;<br/>");
    });
  }
};

// src/views/Lists/SessionListView.ts
var SessionListView = class extends AbstractListView {
  render(data) {
    return __async(this, null, function* () {
      this.dv.span("## Sessions");
      this.dv.table(["&#35;", "Session", "Type", "Synopsis", "Date", "Play Date", "Notes"], data.elements.map((session) => [
        session.id,
        session.link,
        session.type,
        session.synopsis,
        session.date,
        session.irl,
        "[[Notes - " + session.name + "|>>]]"
      ]));
      this.spacer();
    });
  }
};

// src/views/Lists/AdventureListView.ts
var AdventureListView = class extends AbstractListView {
  render(data) {
    return __async(this, null, function* () {
      this.dv.span("## Adventures");
      this.dv.table(["", "Adventure", "Synopsis"], data.elements.map((adventure) => [
        adventure.id,
        adventure.link,
        adventure.synopsis
      ]));
      this.spacer();
    });
  }
};

// src/views/TimelineView.ts
var import_obsidian2 = require("obsidian");
var TimelineView = class extends AbstractListView {
  render(data) {
    return __async(this, null, function* () {
      let response = this.header(data.campaign);
      data.elements.forEach((timeline) => {
        const fileLink = document.createElement("h3");
        import_obsidian2.MarkdownRenderer.renderMarkdown(timeline.link, fileLink, this.dv.currentFilePath, null);
        const synopsis = document.createElement("span");
        import_obsidian2.MarkdownRenderer.renderMarkdown(timeline.synopsis, synopsis, this.dv.currentFilePath, null);
        const date = this.functions.formatDate(timeline.time, "short");
        const time = this.functions.formatTime(timeline.time);
        response += '<li><div class="bullet' + timeline.getEventColour() + '"></div><div class="event-time">' + date + (time !== "00:00" ? "<br/>" + time : "") + '</div><div class="event-type' + timeline.getEventColour() + '">' + timeline.type + '</div><div class="event-details">' + fileLink.outerHTML + synopsis.outerHTML + "</div></li>";
      });
      response += this.footer();
      this.dv.container.innerHTML = response;
    });
  }
  header(campaign) {
    return '<div class="rpgm-container"><div class="rpgm-header"' + ((campaign == null ? void 0 : campaign.imageSrc) !== null ? campaign == null ? void 0 : campaign.imageSrc : "") + '><div class="rpgm-header-overlay"><div class="rpgm-header-title">Timeline</div><div class="rpgm-campaign-name">' + (campaign !== null ? campaign.name : "Campaign") + '</div><div class="rpgm-current-date">' + (campaign !== null ? this.functions.formatDate(campaign.currentDate, "long") : "") + '</div></div></div><div class="rpgm-timeline"><ul>';
  }
  footer() {
    return "</ul></div></div>";
  }
};

// src/views/Lists/CharacterListView.ts
var CharacterListView = class extends AbstractListView {
  render(data) {
    return __async(this, null, function* () {
      this.dv.span("## Characters");
      this.dv.table(["", "Name", "Age", "Synopsis"], data.elements.map((character) => [
        character.image,
        character.link,
        character.age,
        character.synopsis
      ]));
      this.spacer();
    });
  }
};

// src/views/Lists/LocationListView.ts
var LocationListView = class extends AbstractListView {
  render(data) {
    return __async(this, null, function* () {
      this.dv.span("## Locations");
      this.dv.table(["", "Name", "Synopsis"], data.elements.map((character) => [
        character.image,
        character.link,
        character.synopsis
      ]));
      this.spacer();
    });
  }
};

// src/views/Lists/SceneListView.ts
var SceneListView = class extends AbstractListView {
  render(data) {
    return __async(this, null, function* () {
      this.dv.span("## Sessions");
      this.dv.table(["&#35;", "Scene", "Synopsis", "Start", "End", "Duration"], data.elements.map((scene) => [
        scene.sceneId,
        scene.link,
        scene.synopsis,
        scene.startTime,
        scene.endTime,
        scene.duration
      ]));
      this.spacer();
    });
  }
};

// src/factories/RpgViewFactory.ts
var viewType = /* @__PURE__ */ ((viewType2) => {
  viewType2[viewType2["AdventureList"] = 0] = "AdventureList";
  viewType2[viewType2["CharacterList"] = 1] = "CharacterList";
  viewType2[viewType2["Timeline"] = 2] = "Timeline";
  viewType2[viewType2["SessionList"] = 3] = "SessionList";
  viewType2[viewType2["ClueStatus"] = 4] = "ClueStatus";
  viewType2[viewType2["Image"] = 5] = "Image";
  viewType2[viewType2["Synopsis"] = 6] = "Synopsis";
  viewType2[viewType2["ClueRelationshipList"] = 7] = "ClueRelationshipList";
  viewType2[viewType2["LocationList"] = 8] = "LocationList";
  viewType2[viewType2["EventList"] = 9] = "EventList";
  viewType2[viewType2["ClueList"] = 10] = "ClueList";
  viewType2[viewType2["CharacterInfo"] = 11] = "CharacterInfo";
  viewType2[viewType2["FactionList"] = 12] = "FactionList";
  viewType2[viewType2["SceneNavigator"] = 13] = "SceneNavigator";
  viewType2[viewType2["SessionNavigator"] = 14] = "SessionNavigator";
  viewType2[viewType2["SceneList"] = 15] = "SceneList";
  return viewType2;
})(viewType || {});
var RpgViewFactory = class {
  static initialise(functions, app) {
    this.functions = functions;
    this.app = app;
  }
  static createList(viewName, dv) {
    return new views_exports[viewType[viewName] + "View"](this.functions, this.app, dv);
  }
  static createSingle(viewName, dv) {
    return new views_exports[viewType[viewName] + "View"](this.functions, this.app, dv);
  }
};

// src/data/SynopsisData.ts
var SynopsisData = class extends AbstractData {
  constructor(functions, data, title = null) {
    var _a, _b;
    super(functions, data);
    this.title = title;
    this.synopsis = data.synopsis !== null ? data.synopsis : "";
    this.death = ((_a = data.dates) == null ? void 0 : _a.death) !== void 0 && ((_b = data.dates) == null ? void 0 : _b.death) !== void 0 ? this.functions.formatDate(data.dates.death, "short") : "";
    this.isCharacter = data.tags.indexOf("character/npc") !== -1;
  }
};

// src/data/CampaignData.ts
var CampaignData = class extends AbstractImageData {
  constructor(functions, data) {
    super(functions, data);
    this.currentDate = data.dates.current;
  }
};

// src/data/SessionData.ts
var SessionList = class extends AbstractDataList {
  constructor(campaign) {
    super(campaign);
    this.elements = [];
  }
};
var SessionData = class extends AbstractData {
  constructor(functions, data, campaign = null, adventure = null, previousSession = null, nextSession = null) {
    super(functions, data);
    this.campaign = campaign;
    this.adventure = adventure;
    this.previousSession = previousSession;
    this.nextSession = nextSession;
    this.id = data.ids.session;
    this.adventureId = data.ids.adventure;
    this.type = data.ids.type;
    this.synopsis = data.synopsis;
    if (data.dates.session !== null && data.dates.session !== void 0)
      this.date = this.functions.formatDate(data.dates.session, "short");
    if (data.dates.irl !== null && data.dates.irl !== void 0)
      this.date = this.functions.formatDate(data.dates.irl);
  }
};

// src/data/AdventureData.ts
var AdventureList = class extends AbstractDataList {
  constructor(campaign) {
    super(campaign);
    this.elements = [];
  }
};
var AdventureData = class extends AbstractData {
  constructor(functions, data) {
    super(functions, data);
    this.id = data.ids.adventure;
    this.synopsis = data.synopsis;
  }
};

// src/data/CharacterData.ts
var CharacterList = class extends AbstractDataList {
  constructor(campaign) {
    super(campaign);
    this.elements = [];
  }
};
var CharacterData = class extends AbstractImageData {
  constructor(functions, data, campaign, useAdditionalInformation = null) {
    super(functions, data);
    this.campaign = campaign;
    this.age = "";
    this.image = functions.getImage(data);
    if (campaign !== null)
      this.age = functions.calculateAge(data, campaign.currentDate);
    this.isDead = data.dates.death != void 0;
    this.goals = data.goals != void 0 ? data.goals : null;
    this.synopsis = useAdditionalInformation !== null ? useAdditionalInformation : data.synopsis;
  }
};

// src/io/IoData.ts
var IoData = class {
  constructor(functions, campaign, dv) {
    this.functions = functions;
    this.campaign = campaign;
    this.dv = dv;
  }
  getAdventureList() {
    const response = new AdventureList(this.campaign);
    this.dv.pages("#adventure").where((adventure) => adventure.file.folder !== "Templates" && adventure.ids !== null && adventure.ids.adventure !== null).sort((adventure) => -adventure.ids.adventure).forEach((adventure) => {
      response.add(new AdventureData(this.functions, adventure));
    });
    return response;
  }
  getSessionList(adventureId = null) {
    const response = new SessionList(this.campaign);
    this.dv.pages("#session").where((session) => session.file.folder !== "Templates" && session.ids !== null && session.ids.session !== null && (adventureId != null ? session.ids.adventure === adventureId : true)).sort((session) => -session.ids.session).forEach((session) => {
      response.add(new SessionData(this.functions, session));
    });
    return response;
  }
  getCharacterList() {
    const response = new CharacterList(this.campaign);
    this.dv.pages("#character").where((character) => character.file.folder !== "Templates").sort((character) => character.file.name).forEach((character) => {
      response.add(new CharacterData(this.functions, character, this.campaign));
    });
    return response;
  }
};

// src/abstracts/AbstractModel.ts
var AbstractModel = class extends import_obsidian3.MarkdownRenderChild {
  constructor(functions, app, container, source, component, sourcePath) {
    super(container);
    this.functions = functions;
    this.app = app;
    this.container = container;
    this.source = source;
    this.component = component;
    this.sourcePath = sourcePath;
    this.redrawContainer = () => {
      if (this.isActivePage()) {
        this.renderComponent();
      }
    };
  }
  renderComponent(wait = 500) {
    return __async(this, null, function* () {
      setTimeout(() => {
        this.dv = this.app.plugins.plugins.dataview.localApi(this.sourcePath, this.component, this.container);
        const current = this.dv.current();
        if (current != null) {
          this.current = current;
        } else {
          return;
        }
        if (RpgMetadataValidator.validate(this.app, this.current)) {
          const campaigns = this.dv.pages(`#campaign and -"Templates"`);
          if (campaigns !== void 0 && campaigns.length === 1) {
            this.campaign = new CampaignData(this.functions, campaigns[0]);
          } else {
            this.campaign = null;
          }
          this.io = new IoData(this.functions, this.campaign, this.dv);
          this.container.innerHTML = "";
          this.render();
        }
      }, wait);
    });
  }
  onload() {
    this.renderComponent(0);
    this.registerEvent(this.app.workspace.on("rpgmanager:refresh-views", this.redrawContainer));
  }
  isActivePage() {
    var _a, _b, _c, _d;
    const views = this.app.workspace.getLayout().main.children;
    for (let viewCounter = 0; viewCounter < views.length; viewCounter++) {
      if (((_b = (_a = views[viewCounter].state) == null ? void 0 : _a.state) == null ? void 0 : _b.file) !== void 0 && ((_d = (_c = views[viewCounter].state) == null ? void 0 : _c.state) == null ? void 0 : _d.file) === this.sourcePath) {
        return true;
      }
    }
    return false;
  }
  writeData(data, typeOfView) {
    if (data.elements.length > 0) {
      const view = RpgViewFactory.createList(typeOfView, this.dv);
      view.render(data);
    }
  }
  image(width = 75, height = 75) {
    const current = this.dv.current();
    if (current !== void 0) {
      const data = new ImageData(this.functions, current, width, height);
      const view = RpgViewFactory.createSingle(5 /* Image */, this.dv);
      view.render(data);
    }
  }
  synopsis(title = null) {
    const current = this.dv.current();
    if (current !== void 0) {
      const data = new SynopsisData(this.functions, current, title);
      const view = RpgViewFactory.createSingle(6 /* Synopsis */, this.dv);
      view.render(data);
    }
  }
};

// src/data/ClueData.ts
var ClueList = class extends AbstractDataList {
  constructor(campaign) {
    super(campaign);
    this.elements = [];
  }
};
var ClueData = class extends AbstractImageData {
  constructor(functions, data, useAdditionalInformation = null) {
    super(functions, data);
    this.image = functions.getImage(data);
    if (data.dates.found !== null && data.dates.found !== void 0 && data.dates.found !== false) {
      this.found = functions.formatDate(data.dates.found, "long");
    } else {
      this.found = false;
    }
    this.synopsis = useAdditionalInformation !== null ? useAdditionalInformation : data.synopsis;
  }
};

// src/data/EventData.ts
var EventList = class extends AbstractDataList {
  constructor(campaign) {
    super(campaign);
    this.elements = [];
  }
};
var EventData = class extends AbstractImageData {
  constructor(functions, data, campaign, useAdditionalInformation = null) {
    super(functions, data);
    this.campaign = campaign;
    if (data.dates.event != null)
      this.date = this.functions.formatDate(data.dates.event, "short");
    this.synopsis = useAdditionalInformation !== null ? useAdditionalInformation : data.synopsis;
  }
};

// src/data/FactionData.ts
var FactionList = class extends AbstractDataList {
  constructor(campaign) {
    super(campaign);
    this.elements = [];
  }
};
var FactionData = class extends AbstractImageData {
  constructor(functions, data, campaign, useAdditionalInformation = null) {
    super(functions, data);
    this.campaign = campaign;
    this.synopsis = useAdditionalInformation !== null ? useAdditionalInformation : data.synopsis;
  }
};

// src/data/LocationData.ts
var LocationList = class extends AbstractDataList {
  constructor(campaign) {
    super(campaign);
    this.elements = [];
  }
};
var LocationData = class extends AbstractImageData {
  constructor(functions, data, useAdditionalInformation = null) {
    super(functions, data);
    this.address = data.address;
    this.synopsis = useAdditionalInformation !== null ? useAdditionalInformation : data.synopsis;
  }
};

// src/models/RpgNpcModel.ts
var RpgNpcModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      this.synopsis();
      this.image(300, 300);
      this.info();
      this.factionList();
      this.characterList();
      this.eventList();
      this.clueList();
      this.locationList();
    });
  }
  info() {
    return __async(this, null, function* () {
      const current = this.dv.current();
      if (current !== void 0) {
        const data = new CharacterData(this.functions, current, this.campaign);
        const view = RpgViewFactory.createSingle(11 /* CharacterInfo */, this.dv);
        view.render(data);
      }
    });
  }
  factionList() {
    return __async(this, null, function* () {
      const data = new FactionList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0) {
        const factions = this.dv.pages("#faction").where((faction) => {
          var _a, _b;
          return faction.file.folder !== "Templates" && ((_a = current.relationships) == null ? void 0 : _a.factions) != null && ((_b = current.relationships) == null ? void 0 : _b.factions[faction.file.name]) !== void 0;
        });
        factions.forEach((faction) => {
          var _a;
          data.add(new FactionData(this.functions, faction, this.campaign, (_a = current.relationships) == null ? void 0 : _a.factions[faction.file.name]));
        });
        this.writeData(data, 12 /* FactionList */);
      }
    });
  }
  characterList() {
    return __async(this, null, function* () {
      var _a;
      const data = new CharacterList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0 && ((_a = current.relationships) == null ? void 0 : _a.characters) != null) {
        const characters = this.dv.pages("#character").where((page) => {
          var _a2;
          return page.file.folder !== "Templates" && ((_a2 = current.relationships) == null ? void 0 : _a2.characters[page.file.name]) !== void 0;
        });
        characters.forEach((character) => {
          var _a2;
          data.add(new CharacterData(this.functions, character, this.campaign, (_a2 = current.relationships) == null ? void 0 : _a2.characters[character.file.name]));
        });
        this.writeData(data, 1 /* CharacterList */);
      }
    });
  }
  eventList() {
    return __async(this, null, function* () {
      const data = new EventList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0) {
        const events = this.dv.pages("#event").where((event) => {
          var _a, _b;
          return event.file.folder !== "Templates" && ((_a = event.relationships) == null ? void 0 : _a.characters) != null && ((_b = event.relationships) == null ? void 0 : _b.characters[current.file.name]) !== void 0;
        });
        events.forEach((event) => {
          var _a;
          data.add(new EventData(this.functions, event, this.campaign, (_a = event.relationships) == null ? void 0 : _a.characters[current.file.name]));
        });
        this.writeData(data, 9 /* EventList */);
      }
    });
  }
  clueList() {
    return __async(this, null, function* () {
      const data = new ClueList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0) {
        const clues = this.dv.pages("#clue").where((page) => {
          var _a, _b;
          return page.file.folder !== "Templates" && ((_a = page.relationships) == null ? void 0 : _a.characters) != void 0 && ((_b = page.relationships) == null ? void 0 : _b.characters[current.file.name]) !== void 0;
        });
        clues.forEach((clue) => {
          var _a;
          data.add(new ClueData(this.functions, clue, (_a = clue.relationships) == null ? void 0 : _a.characters[current.file.name]));
        });
        this.writeData(data, 10 /* ClueList */);
      }
    });
  }
  locationList() {
    return __async(this, null, function* () {
      var _a;
      const data = new LocationList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0 && ((_a = current.relationships) == null ? void 0 : _a.locations) != null) {
        const locations = this.dv.pages("#location").where((location) => {
          var _a2;
          return location.file.folder !== "Templates" && ((_a2 = current.relationships) == null ? void 0 : _a2.locations[location.file.name]) !== void 0;
        });
        locations.forEach((location) => {
          var _a2;
          data.add(new LocationData(this.functions, location, (_a2 = current.relationships) == null ? void 0 : _a2.locations[location.file.name]));
        });
        this.writeData(data, 8 /* LocationList */);
      }
    });
  }
};

// src/models/RpgErrorModel.ts
var RpgErrorModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      this.container.innerText = "The selected function does not exist in Rpg Manager";
    });
  }
};

// src/models/RpgAdventureModel.ts
var RpgAdventureModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      var _a;
      this.sessionList((_a = this.dv.current()) == null ? void 0 : _a.ids.adventure);
    });
  }
  sessionList(adventureId) {
    return __async(this, null, function* () {
      this.writeData(this.io.getSessionList(adventureId), 3 /* SessionList */);
    });
  }
};

// src/models/RpgCampaignModel.ts
var RpgCampaignModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      this.adventureList();
      this.sessionList();
      this.characterList();
    });
  }
  adventureList() {
    return __async(this, null, function* () {
      this.writeData(this.io.getAdventureList(), 0 /* AdventureList */);
    });
  }
  sessionList() {
    return __async(this, null, function* () {
      this.writeData(this.io.getSessionList(), 3 /* SessionList */);
    });
  }
  characterList() {
    return __async(this, null, function* () {
      this.writeData(this.io.getCharacterList(), 1 /* CharacterList */);
    });
  }
};

// src/models/RpgClueModel.ts
var RpgClueModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      this.status();
      this.image(450);
      this.synopsis();
      this.characterList();
      this.locationList();
      this.eventList();
    });
  }
  status() {
    const current = this.dv.current();
    if (current !== void 0) {
      const data = new ClueData(this.functions, current);
      const view = RpgViewFactory.createSingle(4 /* ClueStatus */, this.dv);
      view.render(data);
    }
  }
  characterList() {
    return __async(this, null, function* () {
      var _a;
      const data = new CharacterList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0 && ((_a = current.relationships) == null ? void 0 : _a.characters) != null) {
        const characters = this.dv.pages("#character").where((page) => {
          var _a2;
          return page.file.folder !== "Templates" && ((_a2 = current.relationships) == null ? void 0 : _a2.characters[page.file.name]) !== void 0;
        });
        characters.forEach((character) => {
          var _a2;
          data.add(new CharacterData(this.functions, character, this.campaign, (_a2 = current.relationships) == null ? void 0 : _a2.characters[character.file.name]));
        });
        this.writeData(data, 1 /* CharacterList */);
      }
    });
  }
  locationList() {
    return __async(this, null, function* () {
      var _a, _b;
      const data = new LocationList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0 && ((_a = current.relationships) == null ? void 0 : _a.locations) !== void 0 && ((_b = current.relationships) == null ? void 0 : _b.locations) !== null) {
        const locations = this.dv.pages("#location").where((location) => {
          var _a2;
          return location.file.folder !== "Templates" && ((_a2 = current.relationships) == null ? void 0 : _a2.locations[location.file.name]) !== void 0;
        });
        locations.forEach((location) => {
          var _a2;
          data.add(new LocationData(this.functions, location, (_a2 = current.relationships) == null ? void 0 : _a2.locations[location.file.name]));
        });
        this.writeData(data, 8 /* LocationList */);
      }
    });
  }
  eventList() {
    return __async(this, null, function* () {
      const data = new EventList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0) {
        const events = this.dv.pages("#event").where((event) => {
          var _a, _b;
          return event.file.folder !== "Templates" && ((_a = event.relationships) == null ? void 0 : _a.clues) != null && ((_b = event.relationships) == null ? void 0 : _b.clues[current.file.name]) !== void 0;
        });
        events.forEach((event) => {
          var _a;
          data.add(new EventData(this.functions, event, this.campaign, (_a = event.relationships) == null ? void 0 : _a.clues[current.file.name]));
        });
        this.writeData(data, 9 /* EventList */);
      }
    });
  }
};

// src/models/RpgEventModel.ts
var RpgEventModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      this.image(450);
      this.synopsis();
      this.characterList();
      this.clueList();
      this.locationList();
    });
  }
  characterList() {
    return __async(this, null, function* () {
      var _a;
      const data = new CharacterList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0 && ((_a = current.relationships) == null ? void 0 : _a.characters) != null) {
        const characters = this.dv.pages("#character").where((page) => {
          var _a2;
          return page.file.folder !== "Templates" && ((_a2 = current.relationships) == null ? void 0 : _a2.characters[page.file.name]) !== void 0;
        });
        characters.forEach((character) => {
          var _a2;
          data.add(new CharacterData(this.functions, character, this.campaign, (_a2 = current.relationships) == null ? void 0 : _a2.characters[character.file.name]));
        });
        this.writeData(data, 1 /* CharacterList */);
      }
    });
  }
  clueList() {
    return __async(this, null, function* () {
      var _a;
      const data = new ClueList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0 && ((_a = current.relationships) == null ? void 0 : _a.clues) != null) {
        const clues = this.dv.pages("#clue").where((page) => {
          var _a2;
          return page.file.folder !== "Templates" && ((_a2 = current.relationships) == null ? void 0 : _a2.clues[page.file.name]) !== void 0;
        });
        clues.forEach((clue) => {
          var _a2;
          data.add(new ClueData(this.functions, clue, (_a2 = current.relationships) == null ? void 0 : _a2.clues[clue.file.name]));
        });
        this.writeData(data, 10 /* ClueList */);
      }
    });
  }
  locationList() {
    return __async(this, null, function* () {
      var _a;
      const data = new LocationList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0 && ((_a = current.relationships) == null ? void 0 : _a.locations) != null) {
        const locations = this.dv.pages("#location").where((page) => {
          var _a2;
          return page.file.folder !== "Templates" && ((_a2 = current.relationships) == null ? void 0 : _a2.locations[page.file.name]) !== void 0;
        });
        locations.forEach((location) => {
          var _a2;
          data.add(new LocationData(this.functions, location, (_a2 = current.relationships) == null ? void 0 : _a2.locations[location.file.name]));
        });
        this.writeData(data, 8 /* LocationList */);
      }
    });
  }
};

// src/models/RpgFactionModel.ts
var RpgFactionModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      this.synopsis();
      this.image(200);
      this.characterList();
      this.locationList();
    });
  }
  characterList() {
    return __async(this, null, function* () {
      const data = new CharacterList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0) {
        const characters = this.dv.pages("#character").where((page) => {
          var _a, _b;
          return page.file.folder !== "Templates" && ((_a = page.relationships) == null ? void 0 : _a.factions) != void 0 && ((_b = page.relationships) == null ? void 0 : _b.factions[current.file.name]) !== void 0;
        });
        characters.forEach((character) => {
          var _a;
          data.add(new CharacterData(this.functions, character, this.campaign, (_a = character.relationships) == null ? void 0 : _a.factions[current.file.name]));
        });
        this.writeData(data, 1 /* CharacterList */);
      }
    });
  }
  locationList() {
    return __async(this, null, function* () {
      var _a;
      const data = new LocationList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0 && ((_a = current.relationships) == null ? void 0 : _a.locations) != null) {
        const locations = this.dv.pages("#location").where((page) => {
          var _a2;
          return page.file.folder !== "Templates" && ((_a2 = current.relationships) == null ? void 0 : _a2.locations[page.file.name]) !== void 0;
        });
        locations.forEach((location) => {
          var _a2;
          data.add(new LocationData(this.functions, location, (_a2 = current.relationships) == null ? void 0 : _a2.locations[location.file.name]));
        });
        this.writeData(data, 8 /* LocationList */);
      }
    });
  }
};

// src/models/RpgLocationModel.ts
var RpgLocationModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      var _a, _b;
      this.synopsis(((_a = this.dv.current()) == null ? void 0 : _a.address) ? (_b = this.dv.current()) == null ? void 0 : _b.address : null);
      this.image(450);
      this.characterList();
      this.eventList();
      this.clueList();
    });
  }
  characterList() {
    return __async(this, null, function* () {
      const data = new CharacterList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0) {
        const characters = this.dv.pages("#character").where((page) => {
          var _a, _b;
          return page.file.folder !== "Templates" && ((_a = page.relationships) == null ? void 0 : _a.locations) != void 0 && ((_b = page.relationships) == null ? void 0 : _b.locations[current.file.name]) !== void 0;
        });
        characters.forEach((character) => {
          var _a;
          data.add(new CharacterData(this.functions, character, this.campaign, (_a = character.relationships) == null ? void 0 : _a.locations[current.file.name]));
        });
        this.writeData(data, 1 /* CharacterList */);
      }
    });
  }
  eventList() {
    return __async(this, null, function* () {
      const data = new EventList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0) {
        const events = this.dv.pages("#event").where((event) => {
          var _a, _b;
          return event.file.folder !== "Templates" && ((_a = event.relationships) == null ? void 0 : _a.locations) != null && ((_b = event.relationships) == null ? void 0 : _b.locations[current.file.name]) !== void 0;
        });
        events.forEach((event) => {
          var _a;
          data.add(new EventData(this.functions, event, this.campaign, (_a = event.relationships) == null ? void 0 : _a.locations[current.file.name]));
        });
        this.writeData(data, 9 /* EventList */);
      }
    });
  }
  clueList() {
    return __async(this, null, function* () {
      const data = new ClueList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0) {
        const clues = this.dv.pages("#clue").where((clue) => {
          var _a, _b;
          return clue.file.folder !== "Templates" && ((_a = clue.relationships) == null ? void 0 : _a.locations) != null && ((_b = clue.relationships) == null ? void 0 : _b.locations[current.file.name]) !== void 0;
        });
        clues.forEach((clue) => {
          var _a;
          data.add(new EventData(this.functions, clue, this.campaign, (_a = clue.relationships) == null ? void 0 : _a.locations[current.file.name]));
        });
        this.writeData(data, 10 /* ClueList */);
      }
    });
  }
};

// src/models/RpgNotesModel.ts
var RpgNotesModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
    });
  }
};

// src/models/RpgPcModel.ts
var RpgPcModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      this.image(300, 300);
      this.factionList();
      this.characterList();
      this.locationList();
    });
  }
  factionList() {
    return __async(this, null, function* () {
      const data = new FactionList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0) {
        const factions = this.dv.pages("#faction").where((faction) => {
          var _a, _b;
          return faction.file.folder !== "Templates" && ((_a = current.relationships) == null ? void 0 : _a.factions) != null && ((_b = current.relationships) == null ? void 0 : _b.factions[faction.file.name]) !== void 0;
        });
        factions.forEach((faction) => {
          var _a;
          data.add(new FactionData(this.functions, faction, this.campaign, (_a = current.relationships) == null ? void 0 : _a.factions[faction.file.name]));
        });
        this.writeData(data, 12 /* FactionList */);
      }
    });
  }
  characterList() {
    return __async(this, null, function* () {
      var _a;
      const data = new CharacterList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0 && ((_a = current.relationships) == null ? void 0 : _a.characters) != null) {
        const characters = this.dv.pages("#character").where((page) => {
          var _a2;
          return page.file.folder !== "Templates" && ((_a2 = current.relationships) == null ? void 0 : _a2.characters[page.file.name]) !== void 0;
        });
        characters.forEach((character) => {
          var _a2;
          data.add(new CharacterData(this.functions, character, this.campaign, (_a2 = current.relationships) == null ? void 0 : _a2.characters[character.file.name]));
        });
        this.writeData(data, 1 /* CharacterList */);
      }
    });
  }
  locationList() {
    return __async(this, null, function* () {
      var _a;
      const data = new LocationList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0 && ((_a = current.relationships) == null ? void 0 : _a.locations) != null) {
        const locations = this.dv.pages("#location").where((location) => {
          var _a2;
          return location.file.folder !== "Templates" && ((_a2 = current.relationships) == null ? void 0 : _a2.locations[location.file.name]) !== void 0;
        });
        locations.forEach((location) => {
          var _a2;
          data.add(new LocationData(this.functions, location, (_a2 = current.relationships) == null ? void 0 : _a2.locations[location.file.name]));
        });
        this.writeData(data, 8 /* LocationList */);
      }
    });
  }
};

// src/data/SceneData.ts
var SceneList = class extends AbstractDataList {
  constructor(campaign) {
    super(campaign);
    this.elements = [];
  }
};
var SceneData = class extends AbstractImageData {
  constructor(functions, data, session = null, adventure = null, previousScene = null, nextScene = null, campaign = null) {
    var _a, _b;
    super(functions, data);
    this.session = session;
    this.adventure = adventure;
    this.previousScene = previousScene;
    this.nextScene = nextScene;
    this.campaign = campaign;
    this.duration = "";
    this.synopsis = data.synopsis != void 0 ? data.synopsis : "";
    this.sessionId = ((_a = data.ids) == null ? void 0 : _a.session) != void 0 ? data.ids.session : 0;
    this.sceneId = ((_b = data.ids) == null ? void 0 : _b.scene) != void 0 ? data.ids.scene : 0;
    this.startTime = this.functions.formatTime(data.time.start);
    this.endTime = this.functions.formatTime(data.time.end);
    if (this.startTime !== "" && this.endTime !== "") {
      this.duration = this.functions.calculateDuration(data.time.start, data.time.end);
    }
  }
};

// src/models/RpgSceneModel.ts
var RpgSceneModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      this.outlinks = [];
      yield this.readOutlinks();
      this.sceneNavigator();
      this.characterList();
      this.locationList();
      this.clueList();
    });
  }
  sceneNavigator() {
    return __async(this, null, function* () {
      const current = this.dv.current();
      if (current != void 0 && current.ids != void 0 && current.ids.scene != void 0 && current.ids.session != void 0) {
        const sessions = this.dv.pages("#session").where((session2) => {
          var _a, _b, _c;
          return session2.file.folder !== "Templates" && session2.ids != void 0 && ((_a = session2.ids) == null ? void 0 : _a.session) != void 0 && ((_b = session2.ids) == null ? void 0 : _b.session) === ((_c = current == null ? void 0 : current.ids) == null ? void 0 : _c.session);
        });
        const session = sessions != void 0 && sessions.length === 1 ? sessions[0] : null;
        const adventures = this.dv.pages("#adventure").where((adventure2) => adventure2.file.folder !== "Templates" && adventure2.ids !== void 0 && adventure2.ids.adventure === session.ids.adventure);
        const adventure = adventures != void 0 && adventures.length === 1 ? adventures[0] : null;
        const previousScenes = this.dv.pages("#scene").where((scene) => scene.file.folder !== "Templates" && scene.ids != void 0 && scene.ids.session === (current == null ? void 0 : current.ids.session) && scene.ids.scene === (current == null ? void 0 : current.ids.scene) - 1);
        const previousScene = previousScenes != void 0 && previousScenes.length === 1 ? previousScenes[0] : null;
        const nextScenes = this.dv.pages("#scene").where((scene) => scene.file.folder !== "Templates" && scene.ids != void 0 && scene.ids.session === (current == null ? void 0 : current.ids.session) && scene.ids.scene === (current == null ? void 0 : current.ids.scene) + 1);
        const nextScene = nextScenes != void 0 && nextScenes.length === 1 ? nextScenes[0] : null;
        const data = new SceneData(this.functions, current, session != void 0 ? new SessionData(this.functions, session) : null, adventure != void 0 ? new AdventureData(this.functions, adventure) : null, previousScene != void 0 ? new SceneData(this.functions, previousScene) : null, nextScene != void 0 ? new SceneData(this.functions, nextScene) : null, this.campaign);
        const view = RpgViewFactory.createSingle(13 /* SceneNavigator */, this.dv);
        view.render(data);
      }
    });
  }
  readOutlinks() {
    const current = this.dv.current();
    if (current != void 0) {
      current.file.outlinks.forEach((file) => {
        const page = this.dv.page(file.path);
        if (page != void 0) {
          this.outlinks.push(page);
        }
      });
    }
  }
  isAlreadyPresent(list, element) {
    let response = false;
    list.elements.forEach((existingElement) => {
      if (element.file.name === existingElement.name) {
        response = true;
        return true;
      }
    });
    return response;
  }
  characterList() {
    return __async(this, null, function* () {
      var _a;
      const data = new CharacterList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0 && ((_a = current.relationships) == null ? void 0 : _a.characters) != null) {
        const characters = this.dv.pages("#character").where((page) => {
          var _a2;
          return page.file.folder !== "Templates" && ((_a2 = current.relationships) == null ? void 0 : _a2.characters[page.file.name]) !== void 0;
        });
        characters.forEach((character) => {
          var _a2;
          data.add(new CharacterData(this.functions, character, this.campaign, (_a2 = current.relationships) == null ? void 0 : _a2.characters[character.file.name]));
        });
        this.outlinks.forEach((character) => {
          if ((character.tags.indexOf("character/npc") !== -1 || character.tags.indexOf("character/pc") !== -1) && !this.isAlreadyPresent(data, character)) {
            data.add(new CharacterData(this.functions, character, this.campaign, "_info in description_"));
          }
        });
        this.writeData(data, 1 /* CharacterList */);
      }
    });
  }
  locationList() {
    return __async(this, null, function* () {
      var _a;
      const data = new LocationList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0) {
        if (((_a = current.relationships) == null ? void 0 : _a.locations) != null) {
          const locations = this.dv.pages("#location").where((location) => {
            var _a2;
            return location.file.folder !== "Templates" && ((_a2 = current.relationships) == null ? void 0 : _a2.locations[location.file.name]) !== void 0;
          });
          locations.forEach((location) => {
            var _a2;
            data.add(new LocationData(this.functions, location, (_a2 = current.relationships) == null ? void 0 : _a2.locations[location.file.name]));
          });
        }
        this.outlinks.forEach((location) => {
          if (location.tags.indexOf("location") !== -1 && !this.isAlreadyPresent(data, location)) {
            data.add(new LocationData(this.functions, location, "_info in description_"));
          }
        });
        this.writeData(data, 8 /* LocationList */);
      }
    });
  }
  clueList() {
    return __async(this, null, function* () {
      const data = new ClueList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0) {
        const clues = this.dv.pages("#clue").where((page) => {
          var _a, _b;
          return page.file.folder !== "Templates" && ((_a = current.relationships) == null ? void 0 : _a.clues) != void 0 && ((_b = current.relationships) == null ? void 0 : _b.clues[page.file.name]) !== void 0;
        });
        clues.forEach((clue) => {
          var _a;
          data.add(new ClueData(this.functions, clue, (_a = current.relationships) == null ? void 0 : _a.clues[clue.file.name]));
        });
        this.outlinks.forEach((clue) => {
          if (clue.tags.indexOf("clue") !== -1 && !this.isAlreadyPresent(data, clue)) {
            data.add(new ClueData(this.functions, clue, "_info in description_"));
          }
        });
        this.writeData(data, 10 /* ClueList */);
      }
    });
  }
};

// src/models/RpgSessionModel.ts
var RpgSessionModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      this.sceneList();
    });
  }
  sceneList() {
    return __async(this, null, function* () {
      const data = new SceneList(this.campaign);
      const current = this.dv.current();
      if (current !== void 0 && current.ids.session != null) {
        const scenes = this.dv.pages("#scene").where((page) => page.file.folder !== "Templates" && page.ids !== void 0 && page.ids.session != void 0 && page.ids.scene != void 0 && page.ids.session === current.ids.session).sort((page) => page.ids.scene);
        scenes.forEach((scene) => {
          data.add(new SceneData(this.functions, scene));
        });
        this.writeData(data, 15 /* SceneList */);
      }
    });
  }
};

// src/models/RpgSessionNavigationModel.ts
var RpgSessionNavigationModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      this.sessionNavigator();
    });
  }
  sessionNavigator() {
    return __async(this, null, function* () {
      const current = this.dv.current();
      if (current != void 0 && current.ids != void 0 && current.ids.session != void 0 && current.ids.adventure != void 0) {
        const adventures = this.dv.pages("#adventure").where((adventure2) => adventure2.file.folder !== "Templates" && adventure2.ids.adventure != void 0 && adventure2.ids.adventure == current.ids.adventure);
        const adventure = adventures != void 0 && adventures.length === 1 ? adventures[0] : null;
        const previousSessions = this.dv.pages("#session").where((session) => session.file.folder !== "Templates" && session.ids.adventure != void 0 && session.ids.session != void 0 && session.ids.adventure === current.ids.adventure && session.ids.session === current.ids.session - 1);
        const previousSession = previousSessions != void 0 && previousSessions.length === 1 ? previousSessions[0] : null;
        const nextSessions = this.dv.pages("#session").where((session) => session.file.folder !== "Templates" && session.ids.adventure != void 0 && session.ids.session != void 0 && session.ids.adventure === current.ids.adventure && session.ids.session === current.ids.session + 1);
        const nextSession = nextSessions != void 0 && nextSessions.length === 1 ? nextSessions[0] : null;
        const data = new SessionData(this.functions, current, this.campaign, adventure != void 0 ? new AdventureData(this.functions, adventure) : null, previousSession != void 0 ? new SessionData(this.functions, previousSession) : null, nextSession != void 0 ? new SessionData(this.functions, nextSession) : null);
        const view = RpgViewFactory.createSingle(14 /* SessionNavigator */, this.dv);
        view.render(data);
      }
    });
  }
};

// src/data/TimelineData.ts
var TimelineList = class extends AbstractDataList {
  constructor(campaign) {
    super(campaign);
    this.elements = [];
  }
  sort() {
    this.elements.sort((a, b) => {
      return a.time - b.time;
    });
  }
};
var TimelineData = class extends AbstractImageData {
  constructor(functions, data, type) {
    super(functions, data);
    this.type = type;
    this.image = functions.getImage(data, 70);
    this.synopsis = data.synopsis;
    switch (data.file.tags[0]) {
      case "event":
        this.time = data.dates.event;
        break;
    }
  }
  getEventColour() {
    switch (this.type) {
      case "event":
        return "";
        break;
      case "birth":
        return " green";
        break;
      case "death":
        return " red";
        break;
      case "session":
        return " blue";
        break;
      case "clue":
        return " purple";
        break;
    }
    return "";
  }
};

// src/models/RpgTimelineModel.ts
var RpgTimelineModel = class extends AbstractModel {
  render() {
    return __async(this, null, function* () {
      const data = new TimelineList(this.campaign);
      const events = this.dv.pages("#event").where((event) => {
        var _a, _b;
        return ((_a = event == null ? void 0 : event.dates) == null ? void 0 : _a.event) !== void 0 && ((_b = event == null ? void 0 : event.dates) == null ? void 0 : _b.event) !== null;
      });
      events.forEach((event) => {
        data.add(new TimelineData(this.functions, event, "event"));
      });
      let characters = this.dv.pages("#character").where((character) => {
        var _a, _b;
        return ((_a = character == null ? void 0 : character.dates) == null ? void 0 : _a.dob) !== void 0 && ((_b = character == null ? void 0 : character.dates) == null ? void 0 : _b.dob) !== null;
      });
      characters.forEach((character) => {
        data.add(new TimelineData(this.functions, character, "birth"));
      });
      characters = this.dv.pages("#character").where((character) => {
        var _a, _b;
        return ((_a = character == null ? void 0 : character.dates) == null ? void 0 : _a.death) !== void 0 && ((_b = character == null ? void 0 : character.dates) == null ? void 0 : _b.death) !== null;
      });
      characters.forEach((character) => {
        character.add(new TimelineData(this.functions, character, "death"));
      });
      const sessions = this.dv.pages("#session").where((session) => {
        var _a, _b;
        return ((_a = session == null ? void 0 : session.dates) == null ? void 0 : _a.session) !== void 0 && ((_b = session == null ? void 0 : session.dates) == null ? void 0 : _b.session) !== null;
      });
      sessions.forEach((session) => {
        data.add(new TimelineData(this.functions, session, "session"));
      });
      const clues = this.dv.pages("#clue").where((clue) => {
        var _a, _b;
        return ((_a = clue == null ? void 0 : clue.dates) == null ? void 0 : _a.found) !== void 0 && ((_b = clue == null ? void 0 : clue.dates) == null ? void 0 : _b.found) !== null;
      });
      clues.forEach((clue) => {
        data.add(new TimelineData(this.functions, clue, "clue"));
      });
      data.sort();
      const view = RpgViewFactory.createList(2 /* Timeline */, this.dv);
      view.render(data);
    });
  }
};

// src/factories/RpgModelFactory.ts
var RpgModelFactory = class {
  static create(functions, app, container, source, component, sourcePath) {
    switch (source.replace(/[\n\r]/g, "").toLowerCase()) {
      case "adventure":
        return new RpgAdventureModel(functions, app, container, source, component, sourcePath);
        break;
      case "campaign":
        return new RpgCampaignModel(functions, app, container, source, component, sourcePath);
        break;
      case "clue":
        return new RpgClueModel(functions, app, container, source, component, sourcePath);
        break;
      case "event":
        return new RpgEventModel(functions, app, container, source, component, sourcePath);
        break;
      case "faction":
        return new RpgFactionModel(functions, app, container, source, component, sourcePath);
        break;
      case "location":
        return new RpgLocationModel(functions, app, container, source, component, sourcePath);
        break;
      case "npc":
        return new RpgNpcModel(functions, app, container, source, component, sourcePath);
        break;
      case "notes":
        return new RpgNotesModel(functions, app, container, source, component, sourcePath);
        break;
      case "pc":
        return new RpgPcModel(functions, app, container, source, component, sourcePath);
        break;
      case "scene":
        return new RpgSceneModel(functions, app, container, source, component, sourcePath);
        break;
      case "session":
        return new RpgSessionModel(functions, app, container, source, component, sourcePath);
        break;
      case "sessionnavigator":
        return new RpgSessionNavigationModel(functions, app, container, source, component, sourcePath);
        break;
      case "timeline":
        return new RpgTimelineModel(functions, app, container, source, component, sourcePath);
        break;
      default:
        return new RpgErrorModel(functions, app, container, source, component, sourcePath);
        break;
    }
  }
};

// src/main.ts
var RpgManager = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.areFunctionsLoaded = false;
  }
  onload() {
    return __async(this, null, function* () {
      console.log("Loading RpgManager " + this.manifest.version);
      this.refreshViews = (0, import_obsidian4.debounce)(this.refreshViews, 2500, true);
      this.registerEvent(this.app.metadataCache.on("resolved", function() {
        this.refreshViews();
      }.bind(this)));
      this.registerEvent(this.app.vault.on("modify", function() {
        this.refreshViews();
      }.bind(this)));
      this.registerPriorityCodeblockPostProcessor("RpgManager", -100, (source, el, ctx) => __async(this, null, function* () {
        return this.createRpgView(source, el, ctx, ctx.sourcePath);
      }));
    });
  }
  refreshViews() {
    this.app.workspace.trigger("rpgmanager:refresh-views");
  }
  createRpgView(source, el, component, sourcePath) {
    return __async(this, null, function* () {
      if (!this.areFunctionsLoaded) {
        this.areFunctionsLoaded = true;
        this.functions = this.addChild(RpgFunctions.create(this.app));
        RpgViewFactory.initialise(this.functions, this.app);
      }
      this.app.plugins.plugins.dataview.api.index.touch();
      component.addChild(RpgModelFactory.create(this.functions, this.app, el, source, component, sourcePath));
    });
  }
  registerPriorityCodeblockPostProcessor(language, priority, processor) {
    const registered = this.registerMarkdownCodeBlockProcessor(language, processor);
    registered.sortOrder = priority;
  }
  registerPriorityMarkdownPostProcessor(priority, processor) {
    const registered = this.registerMarkdownPostProcessor(processor);
    registered.sortOrder = priority;
  }
};
