export enum HeaderResponseType {
	Short,
	Long,
	Half,
	ScenesSelection,
	SessionSelection,
	StoryCircleSelector,
	AbtSelector,
	SceneTypeSelector,
	SceneExcitment,
	SceneRun,
	SceneRunTime,
	SceneAnalyser,
	Pronoun,
	DateSelector,
	DurationSelector,
	FantasyDateSelector,
}
