import {RpgManagerAdvancedSettingsListsInterface} from "./RpgManagerAdvancedSettingsListsInterface";

export interface RpgManagerAdvancedSettingsInterface {
	ActList: RpgManagerAdvancedSettingsListsInterface;
	AdventureList: RpgManagerAdvancedSettingsListsInterface;
	CharacterList: RpgManagerAdvancedSettingsListsInterface;
	ClueList: RpgManagerAdvancedSettingsListsInterface;
	EventList: RpgManagerAdvancedSettingsListsInterface;
	FactionList: RpgManagerAdvancedSettingsListsInterface;
	LocationList: RpgManagerAdvancedSettingsListsInterface;
	MusicList: RpgManagerAdvancedSettingsListsInterface;
	NonPlayerCharacterList: RpgManagerAdvancedSettingsListsInterface;
	SceneList: RpgManagerAdvancedSettingsListsInterface;
	SessionList: RpgManagerAdvancedSettingsListsInterface;
	SubplotList: RpgManagerAdvancedSettingsListsInterface;
}
