export enum ElementType {
	Campaign = "campaign",
	Adventure = "adventure",
	Scene = "scene",
	Session = "session",
	PlayerCharacter = "playercharacter",
	NonPlayerCharacter = "nonplayercharacter",
	Location = "location",
	Event = "event",
	Clue = "clue",
	Faction = "faction",
	Subplot = "subplot",
	Chapter = "chapter",
	Object = "object",
	Monster = "monster",
}
