import {SubModelFactoryInterface} from "./factories/SubModelFactoryInterface";
import {ContentFactoryInterface} from "./factories/ContentFactoryInterface";
import {FileFactoryInterface} from "./factories/FileFactoryInterface";
import {ModalFactoryInterface} from "./factories/ModalFactoryInterface";
import {ModelFactoryInterface} from "./factories/ModelFactoryInterface";
import {PronounFactoryInterface} from "./factories/PronounFactoryInterface";
import {TemplateFactoryInterface} from "./factories/TemplateFactoryInterface";
import {ViewFactoryInterface} from "./factories/ViewFactoryInterface";
import {FetcherFactoryInterface} from "./factories/FetcherFactoryInterface";
import {IdFactoryInterface} from "./factories/IdFactoryInterface";
import {BreadcrumbFactoryInterface} from "./factories/BreadcrumbFactoryInterface";
import {FrontmatterFactoryInterface} from "./factories/FrontmatterFactoryInterface";
import {SorterFactoryInterface} from "./factories/SorterFactoryInterface";
import {CodeBlockEditorFactoryInterface} from "./factories/CodeBlockEditorFactoryInterface";
import {RunningTimeManagerInterface} from "./dataManipulation/RunningTimeManagerInterface";
import {MetadataReaderInterface} from "./dataManipulation/MetadataReaderInterface";
import {DatabaseFactoryInterface} from "../database/factories/interfaces/DatabaseFactoryInterface";
import {ComponentFactoryInterface} from "../database/factories/interfaces/ComponentFactoryInterface";
import {ComponentTypeFactoryInterface} from "./factories/ComponentTypeFactoryInterface";
import {RelationshipTypeFactoryInterface} from "./factories/RelationshipTypeFactoryInterface";
import {SceneTypeFactoryInterface} from "./factories/SceneTypeFactoryInterface";
import {StoryCircleStageFactoryInterface} from "./factories/StoryCircleStageFactoryInterface";
import {AbtStageFactoryInterface} from "./factories/AbtStageFactoryInterface";

export interface FactoriesInterface {
	subModels: SubModelFactoryInterface;
	contents: ContentFactoryInterface;
	component: ComponentFactoryInterface;
	files: FileFactoryInterface;
	modals: ModalFactoryInterface;
	models: ModelFactoryInterface;
	pronouns: PronounFactoryInterface;
	templates: TemplateFactoryInterface;
	views: ViewFactoryInterface;
	fetchers: FetcherFactoryInterface;
	database: DatabaseFactoryInterface;
	id: IdFactoryInterface;
	breadcrumb: BreadcrumbFactoryInterface;
	frontmatter: FrontmatterFactoryInterface;
	sorter: SorterFactoryInterface;
	codeblock: CodeBlockEditorFactoryInterface;
	runningTimeManager: RunningTimeManagerInterface;
	metadataReader: MetadataReaderInterface;
	componentType: ComponentTypeFactoryInterface;
	relationshipType: RelationshipTypeFactoryInterface;
	sceneType: SceneTypeFactoryInterface;
	storyCircleStage: StoryCircleStageFactoryInterface;
	abtStage: AbtStageFactoryInterface;
}
